### ISSUE TITLE
User guide are too simple

### ISSUE THREAD

**Issue by huhongjia** [Bitcoin-com/wormholecash#6]
User Guide:https://developer.bitcoin.com/wormhole/docs/getting-started.html
The project wormholecash relies on https://github.com/Bitcoin-com/wormholerest.bitcoin.com，Need to be clearly stated in the manual。
Due to incomplete interface documentation, after many failures, the following flow chart has been fumbled out：
1、git clone git@github.com:Bitcoin-com/wormholerest.bitcoin.com.git
2、Configure the following parameters：RPC_BASEURL、RPC_USERNAME、RPC_PASSWORD
3、start wormholerest with paramters(default port 3000):
RPC_BASEURL="http://host:port/" RPC_USERNAME=user RPC_PASSWORD=pass node app.js
4、check it。http://localhost:3000/ 
4、npm install wormholecash --global
5、Create new project，wormhole new hello
6、Configure wormhole.js，resetURL=http://localhost:3000/

**Comment by cgcardona** [comment]
Hi. Thanks for the feedback. Yes you are correct the docs need to be better fleshed out.

Initially we were going to create a wormholerest.bitcoin subdomain but instead we're going to have the wormhole REST endpoints on rest.bitcoin.com after sept 1st. 

That should help simplify the workflow. I'll update the docs per your suggestions. Thanks again.

**Comment by cgcardona** [comment]
Our [examples](https://github.com/Bitcoin-com/wormholecash/tree/master/examples) section is much more in depth.
