### ISSUE TITLE
Missing BitBox Classes

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/wormholecash#7]
I'm currently working on migrating my Wormhole code from 0.2.4 to the latest version of 0.5.3. I tried using following this [grant.js](https://gist.github.com/cgcardona/68f9247584ca13ca9d3647e736d79033) example, which uses `Wormhole.Address.utxo` Address class inherited from Bitbox, shown on [Line 22](https://gist.github.com/cgcardona/68f9247584ca13ca9d3647e736d79033#file-grant-js-L22).

Trying to follow that example, I was getting an error trying to use any of the inherited Bitbox classes. The example code below shows that those classes are not attached to the `wormhole` instantiation of `Wormhole`. The result is the same if I use my local wormhole full node, or the bitcoin.com rest service.

```javascript
// wormholecash version 0.5.3
let Wormhole = require("wormholecash/lib/Wormhole").default;
//let wormhole = new Wormhole({ restURL: `http://localhost:3000/v1/` });
let wormhole = new Wormhole({ restURL: `http://trest.bitcoin.com/v1/` });

// Inspect JavaScript objects.
const util = require("util");
util.inspect.defaultOptions = {
  showHidden: true,
  colors: true
};

console.log(`Wormhole: ${util.inspect(Wormhole)}`);
console.log(`wormhole.Address: ${util.inspect(wormhole.Address)}`);

/*
Output:
  Wormhole: { [Function: Wormhole]
  [length]: 1,
  [name]: 'Wormhole',
  [prototype]: Wormhole { [constructor]: [Circular] } }
  
  wormhole.Address: Address { restURL: 'http://trest.bitcoin.com/v1/' }
*/
```

There is every possibility that I'm instantiating thing incorrectly. Please correct me if you see a problem in the code above.

**Comment by christroutner** [comment]
I just realized that I can continue to follow [new syntax](https://gist.github.com/cgcardona/b532e8c01d64ee6b7f8958f9a95412f3) if I instantiate Bitbox separately by adding this code to the top of the script:

```javascript
const BITBOXCli = require("bitbox-cli/lib/bitbox-cli").default;
const BITBOX = new BITBOXCli({ restURL: "https://trest.bitcoin.com/v1/" });
```

And then replacing `Wormhole` with `BITBOX` like this:

`let u = await BITBOX.Address.utxo([BCH_RECIEVER]);`

**Comment by christroutner** [comment]
However, some of the functions in this [grant tokens example](https://gist.github.com/cgcardona/68f9247584ca13ca9d3647e736d79033) do not exist in either Bitbox or Wormhole. For example [this line](https://gist.github.com/cgcardona/68f9247584ca13ca9d3647e736d79033#file-grant-js-L25) uses `RawTransactions.create` which does not exist in the [RawTransaction API documentation](https://developer.bitcoin.com/bitbox/docs/rawtransactions.html)

**Comment by christroutner** [comment]
Did a bit more sleuthing. This does appear to be an issue with the npm package. Including the wormholecash library at the top of my script like this:

`let Wormhole = require("wormholecash/lib/Wormhole").default;`

results in errors as described above when I execute this command:

`let rawTx = await wormhole.RawTransactions.create([utxo], {});`

However, that command passes just fine if I install a local clone of the wormholecash repo, build it, and replace the `require` line above with this:

`let Wormhole = require("../../wormholecash/lib/Wormhole").default`

**Comment by cgcardona** [comment]
This will be resolved when we merge the wormholerest work w/ rest.bitcoin.
